import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import { Box, TextField, Button } from '@mui/material';
import { makeStyles } from '@mui/styles';
import styles from '../styles/Home.module.css';
import { BottomNav } from '../src/components/navigation/BottomNav';
import { jwtDecode, getJwt } from '../src/utils/jwt';
import Forbidden from '../src/components/pages/Forbidden';
import { socketInit } from '../src/utils/socket/index';

const useStyles = makeStyles((theme) => ({
  root: {
    marginTop: '0',
    padding: '4rem 0',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {},
  textField: {
    marginRight: '1rem',
  },
  chatbox: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
    justifyContent: 'center',
    border: '3px solid #ccc',
    borderRadius: '4px',
    marginTop: '1rem',
    marginBottom: '5rem',
    padding: '1rem',
  },
  chatForm: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '464px',
    position: 'fixed',
    bottom: '76px',
    backgroundColor: '#fff',
  },
  chat: {
    margin: '0.5rem 0',
  },
}));

export default function Home() {
  const classes = useStyles();
  const chatboxEnd = useRef(null);
  const [socket, setSocket] = useState(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [user, setUser] = useState({});
  const [messages, setMessages] = useState([]);
  const [message, setMessage] = useState({
    user: user?.username,
    text: '',
  });

  useEffect(() => {
    const { id, username } = jwtDecode();
    if (!id) setIsAuthenticated(false);
    else {
      const jwt = getJwt();
      setUser({ id, username });
      setMessage({ user: username, text: '' });
      setIsAuthenticated(true);
      socketInit(setSocket, jwt);
    }
  }, []);

  useEffect(() => {
    socket?.on('chat', (data) => {
      setMessages((prevState) => [...prevState, data]);
    });
  }, [socket]);

  useEffect(() => {
    chatboxEnd.current?.scrollIntoView({ behavior: "smooth" });
    console.log(chatboxEnd.current?.scrollHeight);
  }, [messages]);

  const sendMessage = (e) => {
    e.preventDefault();
    socket.emit('chat', message);
    setMessage({ ...message, text: '' });
  };

  return (
    <div className={styles.container}>
      {!isAuthenticated ? (
        <Forbidden />
      ) : (
        <>
          <Head>
            <title>Kongke</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <main className={styles.main}>
            <h1 className={styles.title}>
              Welcome to <a href='https://kongke.vercel.app'>Kongke!</a>
            </h1>
            {/* chatbox */}
            <Box className={classes.chatbox}>
              {messages.map((message, index) => (
                <p key={index} className={classes.chat}>
                  <strong>{`${message.user}: `}</strong>
                  {message.text}
                </p>
              ))}
              <div ref={chatboxEnd}></div>
            </Box>
            <form className={classes.chatForm} onSubmit={sendMessage}>
              <TextField
                className={classes.textField}
                label='Type your message here'
                name='chat'
                path='text'
                fullWidth
                value={message.text}
                onChange={(e) => setMessage({ ...message, text: e.target.value })}
              ></TextField>
              <Button type='submit' variant='contained' className={classes.button}>
                Send
              </Button>
            </form>
          </main>
        </>
      )}
      <BottomNav label='Home' />
    </div>
  );
}
